[1,0]<stderr>:2022-10-18 16:25:34.370465: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
[1,0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,1]<stderr>:2022-10-18 16:25:34.370465: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
[1,1]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,2]<stderr>:2022-10-18 16:25:34.370465: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
[1,2]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,3]<stderr>:2022-10-18 16:25:34.370519: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
[1,3]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,3]<stderr>:2022-10-18 16:25:36.450286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30989 MB memory:  -> device: 3, name: Tesla V100-PCIE-32GB, pci bus id: 0000:d8:00.0, compute capability: 7.0
[1,0]<stderr>:2022-10-18 16:25:36.471073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30989 MB memory:  -> device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:06:00.0, compute capability: 7.0
[1,2]<stderr>:2022-10-18 16:25:36.479459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30989 MB memory:  -> device: 2, name: Tesla V100-PCIE-32GB, pci bus id: 0000:86:00.0, compute capability: 7.0
[1,1]<stderr>:2022-10-18 16:25:36.494206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30989 MB memory:  -> device: 1, name: Tesla V100-PCIE-32GB, pci bus id: 0000:2f:00.0, compute capability: 7.0
[1,0]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,2]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,3]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,1]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,0]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,2]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,3]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,1]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,0]<stderr>:2022-10-18 16:25:47.203486: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
[1,3]<stderr>:2022-10-18 16:25:47.215794: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
[1,2]<stderr>:2022-10-18 16:25:47.231727: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
[1,1]<stderr>:2022-10-18 16:25:47.263638: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
[1,0]<stderr>:2022-10-18 16:25:50.255080: W tensorflow/core/kernels/gpu_utils.cc:50] Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.
[1,2]<stderr>:2022-10-18 16:25:50.255207: W tensorflow/core/kernels/gpu_utils.cc:50] Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.
[1,3]<stderr>:2022-10-18 16:25:50.255239: W tensorflow/core/kernels/gpu_utils.cc:50] Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.
[1,1]<stderr>:2022-10-18 16:25:50.255303: W tensorflow/core/kernels/gpu_utils.cc:50] Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.
[1,1]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,2]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,0]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,3]<stderr>:WARNING:tensorflow:Model was constructed with shape (None, 108, 2048) for input KerasTensor(type_spec=TensorSpec(shape=(None, 108, 2048), dtype=tf.float32, name='consolidated_input'), name='consolidated_input', description="created by layer 'consolidated_input'"), but it was called on an input with incompatible shape (None, None, None, None).
[1,0]<stderr>:2022-10-18 16:29:42.885169: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
